# Generated by Django 6.0.6 on 2026-08-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_book_rental"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="rent_price",
        ),
    ]
